### ISSUE TITLE
Restrict the ability to send multiple replies from one device

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/Employee-pulse#111]
In order to reduce spam, we need to block the ability to send responses to the same survey from one device.

When implementing, we should use localStorage. You should create an array in it, e.g. `answeredSurveys` and store all ids of surveys that user answered. When user is sending answer we should check if the surveys is in array and if it is block an action (eg. navigate to home page with toast ‘you already answered in the survey’)

This solution will not guarantee sending several replies by the user (the user can always switch to Incognito mode or clear the browser's memory), but it will only limit this possibility, but because at the moment we do not require logging in to send replies, this is the only solution.

**Comment by Ryczko** [comment]
We can't save client's ID because answering surveys doesn't require logging in. We are unable to protect ourselves against spam otherwise. In the future, we will probably add an option when creating polls that will force the login of the user who wants to answer. However, we certainly do not want to give up the possibility of replying without authorization.

**Comment by akili862002** [comment]
Oh, sorry for the confusion. I meant to say "IP"
Should we gather the client's IP address?
This could help us not only prevent spam but also enable us to potentially introduce a map feature that showcases worldwide submissions.
