### ISSUE TITLE
Create global progress bar indicator

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/Employee-pulse#112]
Sometimes components take a long time to load. To improve the user experience, we should display a progressbar informing about the progress of loading a new page. This will be especially useful when you want to fetch data using `getServerSideProps`.

In case of problems you can follow this article: [https://blog.logrocket.com/how-to-build-a-progress-bar-indicator-in-next-js/](https://blog.logrocket.com/how-to-build-a-progress-bar-indicator-in-next-js/)

**Comment by codezuma** [comment]
@a-lukasiewicz are you implementing this feature.

**Comment by a-lukasiewicz** [comment]
@codezuma You can take this, I will assign it to you.
In case of any questions feel free to ask

**Comment by codezuma** [comment]
@a-lukasiewicz  sure.

**Comment by codezuma** [comment]
@Ryczko can you review the PR.
