### ISSUE TITLE
Add pagination to answers page

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/Employee-pulse#115]
There can be many answers to one survey. We don't need to display them all on one page. We should enable pagination and display e.g. 20 answers on each page. 

At the moment, we only limit the number of displayed components on the page, not the number of answers downloaded from the database.

It would be nice if the pagination functionality was reusable.

**Comment by suleymanbariseser** [comment]
May I work on this feature?

**Comment by Ryczko** [comment]
Sure!

**Comment by Ryczko** [comment]
Great job done by @suleymanbariseser. Thanks again 👏
