### ISSUE TITLE
Option to deactivate/activate survey

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/Employee-pulse#129]
On the survey page, the user should be able to activate or deactivate the survey. A survey that is deactivated should not accept responses from users and inform that the survey is not active. Example desing: 
![image](https://user-images.githubusercontent.com/51440879/229285117-5be595ab-c98a-452c-9a45-b8c306a085b1.png)

That option should use `Toggle` component from shared folder.

**Comment by NiazMorshed2007** [comment]
Hey there!
Would love to work on this.

**Comment by Ryczko** [comment]
Sure!
