### ISSUE TITLE
Logo as SVG

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/Employee-pulse#139]
For now our logo is just a text with special font. This task is about creating the same logo using svg file and use it in all places. Also, remember about responsiveness.
![image](https://user-images.githubusercontent.com/51440879/230776141-94b8e3d5-2c3e-4dd7-a5e9-500240b78d96.png)

**Comment by xdk78** [comment]
Or maybe something new? I have prepared new versions of the logo
1. ![image](https://user-images.githubusercontent.com/9966516/230781488-ddb39fb2-c38e-4ee4-81a1-9987f8d1ad9b.png)
2. ![image](https://user-images.githubusercontent.com/9966516/230781533-f4da6ab6-82fb-4989-8bb8-4f840edf1f2d.png)
3. ![image](https://user-images.githubusercontent.com/9966516/230781570-c4e271a2-6a64-4333-8041-84d7e700da1d.png)
4. ![image](https://user-images.githubusercontent.com/9966516/230781602-5c1fe39a-c387-4e97-b38c-4768a16655ae.png)

**Comment by Ryczko** [comment]
let's leave it as it was. We'd better go simple
