### ISSUE TITLE
Filtering surveys answers by displaying only those with text feedback

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/Employee-pulse#78]
On the page with survey results, the user should be able to view only answers with additional feedback

For this purpose, we should create a checkbox that will allow displaying only such answers.

**Comment by pmatyjasik** [comment]
Create a checkbox inside the survey that will only show responses that have a written field filled in.
![image](https://user-images.githubusercontent.com/73366069/226197309-96125bb8-5934-41a5-ab95-9b59ba7a66aa.png)
