### ISSUE TITLE
Filtering surveys answers by displaying only those with specific emojis

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/Employee-pulse#79]
On the survey results page, the user should only be able to view responses with selected emojis.

For this purpose, we should create a multiselect component containing all selected emojis and display responses in accordance with the selected values.

**Comment by pmatyjasik** [comment]
Create a checkbox inside the survey that will only show responses that have a written field filled in.

![image](https://user-images.githubusercontent.com/73366069/226197153-8c39da88-b4f1-4ce6-9825-124dd0c78b2b.png)
